namespace RakNexus.Protocol;

public enum PacketPriority : byte
{
    IMMEDIATE_PRIORITY = 0,
    HIGH_PRIORITY,
    MEDIUM_PRIORITY,
    LOW_PRIORITY,
    NUMBER_OF_PRIORITIES
}

public enum PacketReliability : byte
{
    UNRELIABLE = 0,
    UNRELIABLE_SEQUENCED,
    RELIABLE,
    RELIABLE_ORDERED,
    RELIABLE_SEQUENCED,
    UNRELIABLE_WITH_ACK_RECEIPT,
    RELIABLE_WITH_ACK_RECEIPT,
    RELIABLE_ORDERED_WITH_ACK_RECEIPT,
    NUMBER_OF_RELIABILITIES
}